### ISSUE TITLE
Feature request snooze options for reminders

### ISSUE THREAD

**Issue by kumaresh0** [sethyuan/logseq-plugin-reminder#1]
Thanks for your work on this plugin, looking forward new features.

**Comment by sethyuan** [comment]
I'm working on this feature right now. 😂

**Comment by sethyuan** [comment]
@kumaresh0  It's implemented now. Please try the new version.

**Comment by kumaresh0** [comment]
great, it works perfectly 

> @kumaresh0 It's implemented now. Please try the new version.
