### ISSUE TITLE
Feature-Request: Fixed reminding time for scheduled or deadline without time?

### ISSUE THREAD

**Issue by mschiff** [sethyuan/logseq-plugin-reminder#11]
Currently there is no reminder for events without a time set.

It would be nice to have some setting, where you can activate a feature so that the plugin will also remind me of events without time for a day at a time specified in the settings , like:
```
  reminding of schedules or deadline without time: true/false (default false)
  reminding time: 08:00
```
What do you think?

**Comment by sethyuan** [comment]
Good idea, I'll see what I can do.

**Comment by sethyuan** [comment]
@mschiff This is implemented now.

**Comment by mschiff** [comment]
Awesome! Will check it out soon!

**Comment by sethyuan** [comment]
@mschiff All bugs and suggestions are handled. Please take a look of the new version.

**Comment by mschiff** [comment]
I just updated to the new version. I really appreciate it, thanks!

I noticed one thing though: Events without time still still have the additional reminders from the _remindings_ setting applied. So this does not seem to work as it should be or as I would expect. What I meant above as my 4th bullet was that reminders without time do not need several reminders a day but just one at the specified time set in the settings (_defaultRemindingTime_)

Thanks again!

**Comment by sethyuan** [comment]
Oh I see, I'll handle it.

**Comment by sethyuan** [comment]
@mschiff Done.

**Comment by mschiff** [comment]
Works, great! Thanks again!
