### ISSUE TITLE
Offer a command to redisplay reminders for a given timeslot after a restart of Logseq [Enhancement]

### ISSUE THREAD

**Issue by acsr** [sethyuan/logseq-plugin-reminder#16]
### Challenge
If you need to close sticky banners or did it by accident (very easy to click wrong), or the link to the reminder block is broken (see below).
It would be very helpful to reissue the display of reminders back from a selected point in time or a given timeframe (start/end).
In case the reminders are important this would be critical to loose a reminder.
I twould be sufficient to do this by a command from the command interface of logseq or from the preferences pane.

P.S.: I am also investigating the tool to export reminders to the OS Reminders app.
programmer: Florian Egermann
url:: https://github.com/flegfleg/logseq-reminders-sync

### Prerequisites
Logseq 0.10.5 Desktop on macOS Ventura 13.6.4 , Reminders v0.8.4

- During Updates of Logseq Reminders keep sticky as banners if you configure macOS Message Cennter to do so.
- After closing an restarting Logseq (e.g. during an update) and then click on a banner, the reference to the graph from the banner does not work anymore (maybe due to using an expired UUID).

**Comment by sethyuan** [comment]
Due to technical details, the plugin is not using native notification API (which requires exposing from Logseq) right now, that means if Logseq is closed, the notifications will disappear too.

Also, I don't think it's appropriate to redisplay notifications upon a restart, you should treat macOS notifications as a temporal and volatile reminder, and not as a task inbox.

**Comment by acsr** [comment]
> I don't think it's appropriate to redisplay notifications upon a restart

I agree with you on this point, I am just thinking about how to retrieve recent reminders on demand. Should not be automated for every restart. I came on this after clicking on an for me important Reminder by accident. This triggers bad emotions and FOMO (Fear Of Missing Out) feelings. Software UX iss often about feelings as well. 

Reminder is a PlugIn that helps you feeling good by not forgetting inportant stuff. The USer Experience with the Logseq Reminder Plugin (including the setup procedure) is (for me) much better than compared with other stuff. 

#### Why is Reminder Plugin cool?
With Logseq you enter Scheduled and Deadline Data in context of more complex relations and get back on point directly from the Reminder. The triggering data is not buried in a proprietary software and can be queried for other tasks and workflows from the same source, but without a need for a structured database. Instead the trigger can be put anywhere in a block that is worth to have a scheduled popup.
