### ISSUE TITLE
Seems don’t work for me 

### ISSUE THREAD

**Issue by bepolymathe** [sethyuan/logseq-plugin-reminder#2]
Hi @sethyuan 

Waiting for this for a long time. Thanks for that... but it don’t work for me with 0.8.10 on linux (Fedora). 
Nothing appeared.

**Comment by sethyuan** [comment]
Oh my, I don't use Linux desktop, and I'm not sure if Linux has some kind of system level notification center.

**Comment by sethyuan** [comment]
Can you use console (ctrl+shift+i) and capture a screenshot of the errors? This should happen at the moment the system notification is supposed to appear.

**Comment by bepolymathe** [comment]
> BTW, did you install the plugin using the marketplace?

Yes ! 



> Can you use console (ctrl+shift+i) and capture a screenshot of the errors? This should happen at the moment the system notification is supposed to appear.

No errors 🤔 

![image](https://user-images.githubusercontent.com/29939805/200600688-f945e565-6791-45b8-94ae-05152e6be814.png)

**Comment by sethyuan** [comment]
Strange. Can you type `Notification.permission` in the console and see what it says?

**Comment by bepolymathe** [comment]
Same behaviour... 

![image](https://user-images.githubusercontent.com/29939805/200604181-57a526d9-0324-46fc-acf0-7b84098de0e7.png)

**Comment by sethyuan** [comment]
You wrote it in the wrong place. You should execute it below "41 issues", after the arrow pointing right.

**Comment by bepolymathe** [comment]
Oups... 
![image](https://user-images.githubusercontent.com/29939805/200609135-a183e98e-3f9d-43cf-9a5e-8bf7b1679389.png)

**Comment by sethyuan** [comment]
I'm out of ideas. It looks like the methods are executed, but still nothing is popping up. I think it may be a bug in Electron (the foundation framework Logseq is built on).

**Comment by bepolymathe** [comment]
All right. I understand. I'll try to look into it on my end and let you know

**Comment by emms007** [comment]
I have the same case with Windows. I see no error, it seems that the plugin is not detecting that it is time to "ring".
Any way to debug further?

**Comment by bepolymathe** [comment]
> I have the same case with Windows

Strange. It works for me on windows machine 🤔

**Comment by sethyuan** [comment]
Sometimes, it's recommended to restart Logseq after installing a plugin.
As of snooze in Windows, it's a known issue. It seems that Electron in Windows does not fire the notification click event. We need to wait for Logseq to update its Electron version to see if it can solve this problem.

**Comment by lobbia** [comment]
my reminder also doesn't work on my win10, no popup. is this because logseq was installed by non admin account?

**Comment by sethyuan** [comment]
@lobbia Be sure you have Logseq running, this is not a system service level alert, so the software has to be running and the respective graph opened in order to work.

**Comment by lobbia** [comment]
oh, no wonder. understood. Thanks!

**Comment by clobrano** [comment]
https://github.com/sethyuan/logseq-plugin-reminder/issues/2#issuecomment-1613315698
This also worked for me

**Comment by clobrano** [comment]
It might be a good idea to report this somehow in the Readme page (or somewhere else) to support Linux users 😊

**Comment by sethyuan** [comment]
Good idea, I will add this to the README file.
