### ISSUE TITLE
There seems no link to the block containing the Reminder in the message or in the popup with the sleeping/close setting

### ISSUE THREAD

**Issue by acsr** [sethyuan/logseq-plugin-reminder#6]
I did not figure out how to get to the triggering block clicking on a link from the message itself.

**Comment by sethyuan** [comment]
I'll add a checkbox in the dialog.

**Comment by sethyuan** [comment]
It's implemented. I added a checkbox (checked by default) that opens the triggering block when the dialog is closed.

**Comment by acsr** [comment]
Sorry for reopening. After using the dialog the Name of the button "Close" makes no sense when the checkbox is checked. Having it semantically kongruent would be cream on the cake.

Can you make the text in the button dynamic?

- If "checked" -> Open Block
- if "unchecked" -> Close

Your effort is welcome if easy possible.

**Comment by sethyuan** [comment]
What if I change "Open triggering block." to "Open triggering block after selection." and "Close" to "Close dialog"?

I'm worried that removing the word "Close" would confuse other users on how to close the dialog.

**Comment by acsr** [comment]
You are right. What about seperating this out:

- The "Open Block" action (no default checkmark), also closing "The Dialog Window"
    - The "Open the containing block" checkmark makes no sense for me with the "Remind me in ..." actions
- The the current **Remind in...**  snoozer buttons, 
    - they also close "The Dialog Window" but do not change the actual repeater, maybe long term time sequences).
- The **Close (Dialog)** button just closes "The Dialog Window"

Why?

- An "Open Block" action button that just closes the dialog and opens the block. 
    - (see below for more useful convenient followup)
- The "Close Dialog" function just closes the dialog, but does not change/disables the repeater 
    - This adds cognitive load: 
        - is the reminder now disabled or not? 
        - Is the deadline/schedule altered now? 

There are two use cases for me opening the block:

1. Working with the block
2. Changing the scheduled or deadline parameters incl. deactivating the repeater

    - When deactivating the reminder I now tend to just remove the repeater code by hand to keep the actual dates as a reference. 
    - In this case `Change Reminder` and `Deactivate Reminder` as addition to `Close Dialog` could help when opening the block and activating the corresponding Calendar Widget. But making this smooth is a complex workload (e.g. event repeater are in general a tricky challenge)

**Comment by sethyuan** [comment]
I removed the checkbox and put a new button that closes the dialog and opening the triggering block at the same time.

BTW, the "remind in" feature does not alter the original scheduled/deadline's time, nor its repeater.

**Comment by acsr** [comment]
Works for me, good solution, simple but effective. THX!
Any other ideas (Changing the Repeater) needs a seperate ticket, but not now.
