### ISSUE TITLE
Feature Request: Multiple Reminder Times

### ISSUE THREAD

**Issue by sourcebert** [sethyuan/logseq-plugin-reminder#8]
Currently, we can set a single reminder time in settings to notify us a certain number of minutes before a task deadline.

It would be amazing if we could have the option to set **multiple** reminder times without making the settings UI too complex. Imagine being able to specify several reminder times, separated by commas, to get alerts at different intervals.

[optional] It would be even better if we could use different time formats for setting reminders. Instead of converting days or weeks into minutes, how about using formats like `1w` for one week or `2d` for two days? This would save us the trouble of manual calculations and make it more convenient to set reminders based on specific timeframes.

BTW Thank you for your efforts! This plugin is a game-changer for keeping track of my scheduled tasks! :+1:

**Comment by sethyuan** [comment]
There is a reminding feature (with several intervals) which pops a dialog up when you click on the notification, you can use that.

![image](https://github.com/sethyuan/logseq-plugin-reminder/assets/3410293/3510c85a-bf02-449a-8575-1890b0bb9fbd)

**Comment by sourcebert** [comment]
Thank you for the suggestion! The pop-up dialog you mentioned is already a very useful feature.

However, my suggestion was to have multiple reminders for every task by default. It would be awesome to get reminders at different times, like one day before, six hours before, in the morning, and right before the deadline. This would really help in staying on top of important tasks.

By the way, I'm using Ubuntu 22.10, and the notification feature works with a workaround that I mentioned in [this comment](https://github.com/sethyuan/logseq-plugin-reminder/issues/2#issuecomment-1613315698).

Thanks again for your efforts! The plugin is already super useful, and I think it should be a core feature in Logseq, maybe with even with individual reminder settings for each TODO item in the inline text.

**Comment by sethyuan** [comment]
I'm not sure. This plugin does not install system-level notifications, it won't work if the respective Logseq graph is not up and running, that is, it's not suitable for long interval notifications nor very important ones.

**Comment by sourcebert** [comment]
I understand. Logseq is not meant to be a full-fledged task manager, so I appreciate your clarification. My main concern was to have the option of being reminded multiple times for a task, even though Logseq needs to be open for the reminders to work. Personally, I keep Logseq open most of the day :grin:

If this feature doesn't seem relevant to you, feel free to close the issue. Thank you for your response!

**Comment by sethyuan** [comment]
@sourcebert , multiple reminder times is implemented, check it out.

**Comment by sethyuan** [comment]
> @sourcebert , multiple reminder times is implemented, check it out.
> 
> I will try to implement multiple reminding times setting per block next.

This is implemented too, you can set block level reminding via the `remindings` property, the value is in the same format as the plugin level setting.
